<a href="https://colab.research.google.com/github/dsatish1252/sqlite-python-implementation/blob/main/HR_Employee_Management_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("hr_employee.db")

# Enable Foreign Keys
conn.execute("PRAGMA foreign_keys = ON;")

print("Database Connected Successfully")

Database Connected Successfully

In [ ]:
def execute_query(query, params=()):
    cursor = conn.cursor()
    cursor.execute(query, params)
    conn.commit()

def read_query(query):
    return pd.read_sql_query(query, conn)

In [ ]:
create_departments = """
CREATE TABLE departments(
    department_id INTEGER PRIMARY KEY,
    department_name TEXT NOT NULL UNIQUE
);
"""

execute_query(create_departments)

OperationalError: table departments already exists

In [ ]:
create_job_roles = """
CREATE TABLE job_roles(
    role_id INTEGER PRIMARY KEY,
    role_title TEXT NOT NULL UNIQUE,
    min_salary REAL NOT NULL CHECK(min_salary>=0),
    max_salary REAL NOT NULL CHECK(max_salary>=min_salary)
);
"""

execute_query(create_job_roles)

In [ ]:
create_employees = """
CREATE TABLE employees(
    employee_id INTEGER PRIMARY KEY,
    employee_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    city TEXT,
    joining_date DATE NOT NULL,
    department_id INTEGER,
    role_id INTEGER,
    status TEXT DEFAULT 'Active'
        CHECK(status IN ('Active','Probation','Resigned')),
    FOREIGN KEY(department_id)
        REFERENCES departments(department_id),
    FOREIGN KEY(role_id)
        REFERENCES job_roles(role_id)
);
"""

execute_query(create_employees)

In [ ]:
create_attendance = """
CREATE TABLE attendance(
    attendance_id INTEGER PRIMARY KEY,
    employee_id INTEGER,
    attendance_date DATE NOT NULL,
    attendance_status TEXT
        CHECK(attendance_status IN ('Present','Absent','Leave','Half Day')),
    FOREIGN KEY(employee_id)
        REFERENCES employees(employee_id),
    UNIQUE(employee_id,attendance_date)
);
"""

execute_query(create_attendance)

In [ ]:
create_payroll = """
CREATE TABLE payroll(
    payroll_id INTEGER PRIMARY KEY,
    employee_id INTEGER,
    salary_month TEXT NOT NULL,
    basic_salary REAL NOT NULL CHECK(basic_salary>=0),
    bonus REAL DEFAULT 0 CHECK(bonus>=0),
    deductions REAL DEFAULT 0 CHECK(deductions>=0),
    payment_status TEXT
        CHECK(payment_status IN ('Paid','Pending','Hold')),
    FOREIGN KEY(employee_id)
        REFERENCES employees(employee_id),
    UNIQUE(employee_id,salary_month)
);
"""

execute_query(create_payroll)

In [ ]:
display(read_query("SELECT * FROM departments"))
display(read_query("SELECT * FROM job_roles"))
display(read_query("SELECT * FROM employees"))
display(read_query("SELECT * FROM attendance"))
display(read_query("SELECT * FROM payroll"))

Empty DataFrame
Columns: [department_id, department_name]
Index: []

Empty DataFrame
Columns: [role_id, role_title, min_salary, max_salary]
Index: []

Empty DataFrame
Columns: [employee_id, employee_name, email, city, joining_date, department_id, role_id, status]
Index: []

Empty DataFrame
Columns: [attendance_id, employee_id, attendance_date, attendance_status]
Index: []

Empty DataFrame
Columns: [payroll_id, employee_id, salary_month, basic_salary, bonus, deductions, payment_status]
Index: []

In [ ]:
departments = [
    (1, "Human Resources"),
    (2, "Information Technology"),
    (3, "Finance"),
    (4, "Sales"),
    (5, "Operations")
]

conn.executemany(
    "INSERT INTO departments VALUES (?, ?)",
    departments
)

conn.commit()

print("Departments inserted successfully.")

Departments inserted successfully.

In [ ]:
job_roles = [
    (1, "HR Executive", 25000, 50000),
    (2, "Software Developer", 40000, 90000),
    (3, "Accountant", 30000, 70000),
    (4, "Sales Executive", 25000, 60000),
    (5, "Operations Associate", 28000, 65000)
]

conn.executemany(
    "INSERT INTO job_roles VALUES (?, ?, ?, ?)",
    job_roles
)

conn.commit()

print("Job roles inserted successfully.")

Job roles inserted successfully.

In [ ]:
employees = [
    (1, "Rahul Kumar", "rahul.kumar@example.com", "Patna", "2026-01-05", 2, 2, "Active"),
    (2, "Priya Singh", "priya.singh@example.com", "Kolkata", "2026-01-08", 1, 1, "Active"),
    (3, "Amit Raj", "amit.raj@example.com", "Delhi", "2026-01-10", 3, 3, "Probation"),
    (4, "Sneha Verma", "sneha.verma@example.com", "Patna", "2026-01-12", 4, 4, "Active"),
    (5, "Aditya Sharma", "aditya.sharma@example.com", "Mumbai", "2026-01-15", 5, 5, "Active")
]

conn.executemany(
    "INSERT INTO employees VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
    employees
)

conn.commit()

print("Employees inserted successfully.")

Employees inserted successfully.

In [ ]:
attendance = [
    (1, 1, "2026-02-01", "Present"),
    (2, 2, "2026-02-01", "Present"),
    (3, 3, "2026-02-01", "Leave"),
    (4, 4, "2026-02-01", "Half Day"),
    (5, 5, "2026-02-01", "Absent")
]

conn.executemany(
    "INSERT INTO attendance VALUES (?, ?, ?, ?)",
    attendance
)

conn.commit()

print("Attendance inserted successfully.")

Attendance inserted successfully.

In [ ]:
payroll = [
    (1, 1, "2026-02", 35000, 2000, 1000, "Paid"),
    (2, 2, "2026-02", 80000, 5000, 2000, "Paid"),
    (3, 3, "2026-02", 45000, 0, 1000, "Pending"),
    (4, 4, "2026-02", 30000, 3000, 500, "Paid"),
    (5, 5, "2026-02", 28000, 0, 0, "Hold")
]

conn.executemany(
    "INSERT INTO payroll VALUES (?, ?, ?, ?, ?, ?, ?)",
    payroll
)

conn.commit()

print("Payroll records inserted successfully.")

Payroll records inserted successfully.

In [ ]:
print("Departments")
display(read_query("SELECT * FROM departments"))

print("Job Roles")
display(read_query("SELECT * FROM job_roles"))

print("Employees")
display(read_query("SELECT * FROM employees"))

print("Attendance")
display(read_query("SELECT * FROM attendance"))

print("Payroll")
display(read_query("SELECT * FROM payroll"))

Departments

   department_id         department_name
0              1         Human Resources
1              2  Information Technology
2              3                 Finance
3              4                   Sales
4              5              Operations

Job Roles

   role_id            role_title  min_salary  max_salary
0        1          HR Executive     25000.0     50000.0
1        2    Software Developer     40000.0     90000.0
2        3            Accountant     30000.0     70000.0
3        4       Sales Executive     25000.0     60000.0
4        5  Operations Associate     28000.0     65000.0

Employees

,employee_id,employee_name,email,city,joining_date,department_id,role_id,status
0,1,Rahul Kumar,rahul.kumar@example.com,Patna,2026-01-05,2,2,Active
1,2,Priya Singh,priya.singh@example.com,Kolkata,2026-01-08,1,1,Active
2,3,Amit Raj,amit.raj@example.com,Delhi,2026-01-10,3,3,Probation
3,4,Sneha Verma,sneha.verma@example.com,Patna,2026-01-12,4,4,Active
4,5,Aditya Sharma,aditya.sharma@example.com,Mumbai,2026-01-15,5,5,Active

Attendance

   attendance_id  employee_id attendance_date attendance_status
0              1            1      2026-02-01           Present
1              2            2      2026-02-01           Present
2              3            3      2026-02-01             Leave
3              4            4      2026-02-01          Half Day
4              5            5      2026-02-01            Absent

Payroll

,payroll_id,employee_id,salary_month,basic_salary,bonus,deductions,payment_status
0,1,1,2026-02,35000.0,2000.0,1000.0,Paid
1,2,2,2026-02,80000.0,5000.0,2000.0,Paid
2,3,3,2026-02,45000.0,0.0,1000.0,Pending
3,4,4,2026-02,30000.0,3000.0,500.0,Paid
4,5,5,2026-02,28000.0,0.0,0.0,Hold

In [ ]:
def read_query(query):
    return pd.read_sql_query(query, conn)

In [ ]:
print("Departments Table")
display(read_query("SELECT * FROM departments;"))

Departments Table

   department_id         department_name
0              1         Human Resources
1              2  Information Technology
2              3                 Finance
3              4                   Sales
4              5              Operations

In [ ]:
print("Job Roles Table")
display(read_query("SELECT * FROM job_roles;"))

Job Roles Table

   role_id            role_title  min_salary  max_salary
0        1          HR Executive     25000.0     50000.0
1        2    Software Developer     40000.0     90000.0
2        3            Accountant     30000.0     70000.0
3        4       Sales Executive     25000.0     60000.0
4        5  Operations Associate     28000.0     65000.0

In [ ]:
display(read_query("""
SELECT * FROM employees;
"""))

,employee_id,employee_name,email,city,joining_date,department_id,role_id,status
0,1,Rahul Kumar,rahul.kumar@example.com,Patna,2026-01-05,2,2,Active
1,2,Priya Singh,priya.singh@example.com,Kolkata,2026-01-08,1,1,Active
2,3,Amit Raj,amit.raj@example.com,Delhi,2026-01-10,3,3,Probation
3,4,Sneha Verma,sneha.verma@example.com,Patna,2026-01-12,4,4,Active
4,5,Aditya Sharma,aditya.sharma@example.com,Mumbai,2026-01-15,5,5,Active

In [ ]:
display(read_query("""
SELECT employee_name, email, city
FROM employees;
"""))

   employee_name                      email     city
0    Rahul Kumar    rahul.kumar@example.com    Patna
1    Priya Singh    priya.singh@example.com  Kolkata
2       Amit Raj       amit.raj@example.com    Delhi
3    Sneha Verma    sneha.verma@example.com    Patna
4  Aditya Sharma  aditya.sharma@example.com   Mumbai

In [ ]:
display(read_query("""
SELECT *
FROM employees
WHERE city = 'Patna';
"""))

,employee_id,employee_name,email,city,joining_date,department_id,role_id,status
0,1,Rahul Kumar,rahul.kumar@example.com,Patna,2026-01-05,2,2,Active
1,4,Sneha Verma,sneha.verma@example.com,Patna,2026-01-12,4,4,Active

In [ ]:
display(read_query("""
SELECT *
FROM employees
WHERE status = 'Active';
"""))

,employee_id,employee_name,email,city,joining_date,department_id,role_id,status
0,1,Rahul Kumar,rahul.kumar@example.com,Patna,2026-01-05,2,2,Active
1,2,Priya Singh,priya.singh@example.com,Kolkata,2026-01-08,1,1,Active
2,4,Sneha Verma,sneha.verma@example.com,Patna,2026-01-12,4,4,Active
3,5,Aditya Sharma,aditya.sharma@example.com,Mumbai,2026-01-15,5,5,Active

In [ ]:
display(read_query("""
SELECT
    e.employee_name,
    p.basic_salary
FROM employees e
JOIN payroll p
ON e.employee_id = p.employee_id
ORDER BY p.basic_salary DESC
LIMIT 3;
"""))

  employee_name  basic_salary
0   Priya Singh       80000.0
1      Amit Raj       45000.0
2   Rahul Kumar       35000.0

In [ ]:
display(read_query("""
SELECT *
FROM payroll
WHERE payment_status = 'Pending';
"""))

,payroll_id,employee_id,salary_month,basic_salary,bonus,deductions,payment_status
0,3,3,2026-02,45000.0,0.0,1000.0,Pending

In [ ]:
display(read_query("""
SELECT
    e.employee_name,
    d.department_name,
    e.status
FROM employees e
JOIN departments d
ON e.department_id = d.department_id;
"""))

   employee_name         department_name     status
0    Rahul Kumar  Information Technology     Active
1    Priya Singh         Human Resources     Active
2       Amit Raj                 Finance  Probation
3    Sneha Verma                   Sales     Active
4  Aditya Sharma              Operations     Active

In [ ]:
display(read_query("""
SELECT
    e.employee_name,
    j.role_title,
    e.city
FROM employees e
JOIN job_roles j
ON e.role_id = j.role_id;
"""))

   employee_name            role_title     city
0    Rahul Kumar    Software Developer    Patna
1    Priya Singh          HR Executive  Kolkata
2       Amit Raj            Accountant    Delhi
3    Sneha Verma       Sales Executive    Patna
4  Aditya Sharma  Operations Associate   Mumbai

In [ ]:
display(read_query("""
SELECT
    e.employee_name,
    p.salary_month,
    p.basic_salary,
    p.bonus,
    p.deductions,
    p.payment_status
FROM payroll p
JOIN employees e
ON p.employee_id = e.employee_id;
"""))

   employee_name salary_month  basic_salary   bonus  deductions payment_status
0    Rahul Kumar      2026-02       35000.0  2000.0      1000.0           Paid
1    Priya Singh      2026-02       80000.0  5000.0      2000.0           Paid
2       Amit Raj      2026-02       45000.0     0.0      1000.0        Pending
3    Sneha Verma      2026-02       30000.0  3000.0       500.0           Paid
4  Aditya Sharma      2026-02       28000.0     0.0         0.0           Hold

In [ ]:
insert_employee = """
INSERT INTO employees
(employee_name, email, city, joining_date, department_id, role_id, status)
VALUES (?, ?, ?, ?, ?, ?, ?)
"""

new_employee = (
    "Rohan Das",
    "rohan.hr@example.com",
    "Pune",
    "2026-02-15",
    1,      # Human Resources
    1,      # HR Executive
    "Probation"
)

execute_query(insert_employee, new_employee)

print("New employee inserted successfully.")

New employee inserted successfully.

In [ ]:
display(read_query("""
SELECT *
FROM employees
WHERE email='rohan.hr@example.com';
"""))

,employee_id,employee_name,email,city,joining_date,department_id,role_id,status
0,6,Rohan Das,rohan.hr@example.com,Pune,2026-02-15,1,1,Probation

In [ ]:
update_city = """
UPDATE employees
SET city=?
WHERE email=?;
"""

execute_query(update_city, ("Bengaluru", "rohan.hr@example.com"))

print("City updated successfully.")

City updated successfully.

In [ ]:
display(read_query("""
SELECT *
FROM employees
WHERE email='rohan.hr@example.com';
"""))

,employee_id,employee_name,email,city,joining_date,department_id,role_id,status
0,6,Rohan Das,rohan.hr@example.com,Bengaluru,2026-02-15,1,1,Probation

In [ ]:
update_status = """
UPDATE employees
SET status=?
WHERE email=?;
"""

execute_query(update_status, ("Active", "rohan.hr@example.com"))

print("Employee status updated successfully.")

Employee status updated successfully.

In [ ]:
display(read_query("""
SELECT *
FROM employees
WHERE email='rohan.hr@example.com';
"""))

,employee_id,employee_name,email,city,joining_date,department_id,role_id,status
0,6,Rohan Das,rohan.hr@example.com,Bengaluru,2026-02-15,1,1,Active

In [ ]:
display(read_query("""
SELECT *
FROM attendance
WHERE employee_id = (
    SELECT employee_id
    FROM employees
    WHERE email='rohan.hr@example.com'
);
"""))

Empty DataFrame
Columns: [attendance_id, employee_id, attendance_date, attendance_status]
Index: []

In [ ]:
display(read_query("""
SELECT *
FROM payroll
WHERE employee_id = (
    SELECT employee_id
    FROM employees
    WHERE email='rohan.hr@example.com'
);
"""))

Empty DataFrame
Columns: [payroll_id, employee_id, salary_month, basic_salary, bonus, deductions, payment_status]
Index: []

In [ ]:
delete_employee = """
DELETE FROM employees
WHERE email=?;
"""

execute_query(delete_employee, ("rohan.hr@example.com",))

print("Employee deleted successfully.")

Employee deleted successfully.

In [ ]:
display(read_query("""
SELECT *
FROM employees;
"""))

,employee_id,employee_name,email,city,joining_date,department_id,role_id,status
0,1,Rahul Kumar,rahul.kumar@example.com,Patna,2026-01-05,2,2,Active
1,2,Priya Singh,priya.singh@example.com,Kolkata,2026-01-08,1,1,Active
2,3,Amit Raj,amit.raj@example.com,Delhi,2026-01-10,3,3,Probation
3,4,Sneha Verma,sneha.verma@example.com,Patna,2026-01-12,4,4,Active
4,5,Aditya Sharma,aditya.sharma@example.com,Mumbai,2026-01-15,5,5,Active

In [ ]:
display(read_query("""
SELECT *
FROM employees
WHERE email='rohan.hr@example.com';
"""))

Empty DataFrame
Columns: [employee_id, employee_name, email, city, joining_date, department_id, role_id, status]
Index: []

In [ ]:
try:
    execute_query("""
    INSERT INTO employees
    (employee_name, email, city, joining_date, department_id, role_id, status)
    VALUES (?, ?, ?, ?, ?, ?, ?)
    """, (
        "Test Employee",
        "rahul.kumar@example.com",   # Already exists
        "Hyderabad",
        "2026-03-01",
        1,
        1,
        "Active"
    ))
except Exception as e:
    print("Duplicate Email Test:")
    print(e)

Duplicate Email Test:
UNIQUE constraint failed: employees.email

In [ ]:
try:
    execute_query("""
    INSERT INTO employees
    (employee_name, email, city, joining_date, department_id, role_id, status)
    VALUES (?, ?, ?, ?, ?, ?, ?)
    """, (
        "Invalid Department",
        "invaliddept@example.com",
        "Chennai",
        "2026-03-01",
        99,      # Department does not exist
        1,
        "Active"
    ))
except Exception as e:
    print("Invalid Department Test:")
    print(e)

Invalid Department Test:
FOREIGN KEY constraint failed

In [ ]:
try:
    execute_query("""
    INSERT INTO employees
    (employee_name, email, city, joining_date, department_id, role_id, status)
    VALUES (?, ?, ?, ?, ?, ?, ?)
    """, (
        "Invalid Role",
        "invalidrole@example.com",
        "Delhi",
        "2026-03-01",
        1,
        99,      # Role does not exist
        "Active"
    ))
except Exception as e:
    print("Invalid Job Role Test:")
    print(e)

Invalid Job Role Test:
FOREIGN KEY constraint failed

In [ ]:
try:
    execute_query("""
    INSERT INTO employees
    (employee_name, email, city, joining_date, department_id, role_id, status)
    VALUES (?, ?, ?, ?, ?, ?, ?)
    """, (
        "Wrong Status",
        "wrongstatus@example.com",
        "Pune",
        "2026-03-01",
        1,
        1,
        "Joined"      # Invalid status
    ))
except Exception as e:
    print("Invalid Employee Status Test:")
    print(e)

Invalid Employee Status Test:
CHECK constraint failed: status IN ('Active','Probation','Resigned')

In [ ]:
try:
    execute_query("""
    INSERT INTO attendance
    (attendance_id, employee_id, attendance_date, attendance_status)
    VALUES (?, ?, ?, ?)
    """, (
        6,
        1,
        "2026-02-01",   # Already exists for employee 1
        "Present"
    ))
except Exception as e:
    print("Duplicate Attendance Test:")
    print(e)

Duplicate Attendance Test:
UNIQUE constraint failed: attendance.employee_id, attendance.attendance_date

In [ ]:
try:
    execute_query("""
    INSERT INTO attendance
    (attendance_id, employee_id, attendance_date, attendance_status)
    VALUES (?, ?, ?, ?)
    """, (
        7,
        2,
        "2026-02-02",
        "Late"     # Invalid status
    ))
except Exception as e:
    print("Invalid Attendance Status Test:")
    print(e)

Invalid Attendance Status Test:
CHECK constraint failed: attendance_status IN ('Present','Absent','Leave','Half Day')

In [ ]:
try:
    execute_query("""
    INSERT INTO payroll
    (payroll_id, employee_id, salary_month, basic_salary, bonus, deductions, payment_status)
    VALUES (?, ?, ?, ?, ?, ?, ?)
    """, (
        6,
        1,
        "2026-02",   # Already exists for employee 1
        36000,
        1000,
        500,
        "Paid"
    ))
except Exception as e:
    print("Duplicate Payroll Test:")
    print(e)

Duplicate Payroll Test:
UNIQUE constraint failed: payroll.employee_id, payroll.salary_month

In [ ]:
try:
    execute_query("""
    INSERT INTO payroll
    (payroll_id, employee_id, salary_month, basic_salary, bonus, deductions, payment_status)
    VALUES (?, ?, ?, ?, ?, ?, ?)
    """, (
        7,
        2,
        "2026-03",
        -50000,    # Negative salary
        2000,
        500,
        "Paid"
    ))
except Exception as e:
    print("Negative Salary Test:")
    print(e)

Negative Salary Test:
CHECK constraint failed: basic_salary>=0

In [ ]:
try:
    execute_query("""
    INSERT INTO payroll
    (payroll_id, employee_id, salary_month, basic_salary, bonus, deductions, payment_status)
    VALUES (?, ?, ?, ?, ?, ?, ?)
    """, (
        8,
        2,
        "2026-03",
        50000,
        2000,
        500,
        "Processing"   # Invalid status
    ))
except Exception as e:
    print("Invalid Payroll Status Test:")
    print(e)

Invalid Payroll Status Test:
CHECK constraint failed: payment_status IN ('Paid','Pending','Hold')

### **Inspect the Schema**

In [ ]:
print("Departments Table Schema")
display(read_query("PRAGMA table_info(departments);"))

Departments Table Schema

   cid             name     type  notnull dflt_value  pk
0    0    department_id  INTEGER        0       None   1
1    1  department_name     TEXT        1       None   0

In [ ]:
print("Job Roles Table Schema")
display(read_query("PRAGMA table_info(job_roles);"))

Job Roles Table Schema

   cid        name     type  notnull dflt_value  pk
0    0     role_id  INTEGER        0       None   1
1    1  role_title     TEXT        1       None   0
2    2  min_salary     REAL        1       None   0
3    3  max_salary     REAL        1       None   0

In [ ]:
print("Employees Table Schema")
display(read_query("PRAGMA table_info(employees);"))

Employees Table Schema

   cid           name     type  notnull dflt_value  pk
0    0    employee_id  INTEGER        0       None   1
1    1  employee_name     TEXT        1       None   0
2    2          email     TEXT        1       None   0
3    3           city     TEXT        0       None   0
4    4   joining_date     DATE        1       None   0
5    5  department_id  INTEGER        0       None   0
6    6        role_id  INTEGER        0       None   0
7    7         status     TEXT        0   'Active'   0

In [ ]:
print("Attendance Table Schema")
display(read_query("PRAGMA table_info(attendance);"))

Attendance Table Schema

   cid               name     type  notnull dflt_value  pk
0    0      attendance_id  INTEGER        0       None   1
1    1        employee_id  INTEGER        0       None   0
2    2    attendance_date     DATE        1       None   0
3    3  attendance_status     TEXT        0       None   0

In [ ]:
print("Payroll Table Schema")
display(read_query("PRAGMA table_info(payroll);"))

Payroll Table Schema

   cid            name     type  notnull dflt_value  pk
0    0      payroll_id  INTEGER        0       None   1
1    1     employee_id  INTEGER        0       None   0
2    2    salary_month     TEXT        1       None   0
3    3    basic_salary     REAL        1       None   0
4    4           bonus     REAL        0          0   0
5    5      deductions     REAL        0          0   0
6    6  payment_status     TEXT        0       None   0

**Foreign Key Relationships Inspection**

In [ ]:
print("Employees Foreign Keys")
display(read_query("PRAGMA foreign_key_list(employees);"))

Employees Foreign Keys

,id,seq,table,from,to,on_update,on_delete,match
0,0,0,job_roles,role_id,role_id,NO ACTION,NO ACTION,NONE
1,1,0,departments,department_id,department_id,NO ACTION,NO ACTION,NONE

In [ ]:
print("Attendance Foreign Keys")
display(read_query("PRAGMA foreign_key_list(attendance);"))

Attendance Foreign Keys

   id  seq      table         from           to  on_update  on_delete match
0   0    0  employees  employee_id  employee_id  NO ACTION  NO ACTION  NONE

In [ ]:
print("Payroll Foreign Keys")
display(read_query("PRAGMA foreign_key_list(payroll);"))

Payroll Foreign Keys

   id  seq      table         from           to  on_update  on_delete match
0   0    0  employees  employee_id  employee_id  NO ACTION  NO ACTION  NONE

In [ ]:
from IPython.display import HTML, display

tables = ["payroll" ,"employees", "attendance", "job_roles", "departments" ]

html_content = "<table style='width:100%'>"
for i in range(0, len(tables), 4): # Change step to 4 for 4 columns
    html_content += "<tr>"
    for j in range(4): # Loop for 4 columns
        if i + j < len(tables):
            table_name = tables[i + j]
            df = read_query(f"PRAGMA table_info({table_name});")
            html_content += f"<td style='width:25%; vertical-align:top; padding:10px;'>" # Adjust width for 4 columns
            html_content += f"<h3>===== {table_name.upper()} TABLE SCHEMA =====</h3>"
            html_content += df.to_html()
            html_content += "</td>"
        else:
            html_content += "<td style='width:25%;'></td>" # Empty cell to maintain layout
    html_content += "</tr>"
html_content += "</table>"

display(HTML(html_content))