<a href="https://colab.research.google.com/github/dsatish1252/sqlite-python-implementation/blob/main/Numpy_Pandas_File_Handeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Task 7: Text File Handling

marks_list = [85, 92, 76, 88, 69, 91, 55, 78, 39, 95]

total_students = len(marks_list)
average_marks = sum(marks_list) / total_students
highest_marks = max(marks_list)
lowest_marks = min(marks_list)
passed_students = len([m for m in marks_list if m >= 40])
failed_students = len([m for m in marks_list if m < 40])

with open("student_summary.txt", "w") as file:
    file.write("Student Performance Summary\n")
    file.write("----------------------------\n")
    file.write(f"Total Students: {total_students}\n")
    file.write(f"Average Marks: {average_marks:.2f}\n")
    file.write(f"Highest Marks: {highest_marks}\n")
    file.write(f"Lowest Marks: {lowest_marks}\n")
    file.write(f"Passed Students: {passed_students}\n")
    file.write(f"Failed Students: {failed_students}\n")

print("student_summary.txt created successfully.")

print("\nReading File\n")

with open("student_summary.txt","r") as file:
    print(file.read())

student_summary.txt created successfully.

Reading File

Student Performance Summary
----------------------------
Total Students: 10
Average Marks: 76.80
Highest Marks: 95
Lowest Marks: 39
Passed Students: 9
Failed Students: 1

In [ ]:
import csv

students = [
[1,"Rahul",22,"Patna","Python",85,92],
[2,"Priya",24,"Delhi","Data Science",92,88],
[3,"Aman",21,"Kolkata","Python",76,81],
[4,"Neha",23,"Mumbai","Analytics",88,95],
[5,"Rohan",25,"Patna","Python",69,72],
[6,"Simran",22,"Delhi","Data Science",91,89],
[7,"Vikash",24,"Patna","Analytics",55,68],
[8,"Pooja",21,"Kolkata","Python",78,84],
[9,"Arjun",23,"Mumbai","Data Science",39,60],
[10,"Sneha",22,"Delhi","Python",95,97]
]

header = [
"Student_ID",
"Name",
"Age",
"City",
"Course",
"Marks",
"Attendance_Percentage"
]

with open("students.csv","w",newline="") as file:
    writer = csv.writer(file)
    writer.writerow(header)
    writer.writerows(students)

print("students.csv created successfully.")

print("\nStudent Records\n")

with open("students.csv","r") as file:
    reader = csv.reader(file)

    for row in reader:
        print(row)

students.csv created successfully.

Student Records

['Student_ID', 'Name', 'Age', 'City', 'Course', 'Marks', 'Attendance_Percentage']
['1', 'Rahul', '22', 'Patna', 'Python', '85', '92']
['2', 'Priya', '24', 'Delhi', 'Data Science', '92', '88']
['3', 'Aman', '21', 'Kolkata', 'Python', '76', '81']
['4', 'Neha', '23', 'Mumbai', 'Analytics', '88', '95']
['5', 'Rohan', '25', 'Patna', 'Python', '69', '72']
['6', 'Simran', '22', 'Delhi', 'Data Science', '91', '89']
['7', 'Vikash', '24', 'Patna', 'Analytics', '55', '68']
['8', 'Pooja', '21', 'Kolkata', 'Python', '78', '84']
['9', 'Arjun', '23', 'Mumbai', 'Data Science', '39', '60']
['10', 'Sneha', '22', 'Delhi', 'Python', '95', '97']

In [ ]:
import numpy as np

marks = np.array([85,92,76,88,69,91,55,78,39,95])

print("Total Marks :", np.sum(marks))
print("Average Marks :", np.mean(marks))
print("Highest Marks :", np.max(marks))
print("Lowest Marks :", np.min(marks))
print("Standard Deviation :", round(np.std(marks),2))

Total Marks : 768
Average Marks : 76.8
Highest Marks : 95
Lowest Marks : 39
Standard Deviation : 17.1

In [ ]:
import numpy as np

marks = np.array([85,92,76,88,69,91,55,78,39,95])

print(np.sum(marks))
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))
print(round(np.std(marks),2))

768
76.8
95
39
17.1

In [ ]:
import pandas as pd

df = pd.read_csv("students.csv")

print("First Five Rows")
display(df.head())

print("Last Five Rows")
display(df.tail())

print("Shape")
print(df.shape)

print("\nColumns")
print(df.columns)

print("\nInformation")
df.info()

print("\nStatistical Summary")
display(df.describe())

First Five Rows

   Student_ID   Name  Age     City        Course  Marks  Attendance_Percentage
0           1  Rahul   22    Patna        Python     85                     92
1           2  Priya   24    Delhi  Data Science     92                     88
2           3   Aman   21  Kolkata        Python     76                     81
3           4   Neha   23   Mumbai     Analytics     88                     95
4           5  Rohan   25    Patna        Python     69                     72

Last Five Rows

,Student_ID,Name,Age,City,Course,Marks,Attendance_Percentage
5,6,Simran,22,Delhi,Data Science,91,89
6,7,Vikash,24,Patna,Analytics,55,68
7,8,Pooja,21,Kolkata,Python,78,84
8,9,Arjun,23,Mumbai,Data Science,39,60
9,10,Sneha,22,Delhi,Python,95,97

Shape
(10, 7)

Columns
Index(['Student_ID', 'Name', 'Age', 'City', 'Course', 'Marks',
       'Attendance_Percentage'],
      dtype='object')

Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             10 non-null     int64
 1   Name                   10 non-null     object
 2   Age                    10 non-null     int64
 3   City                   10 non-null     object
 4   Course                 10 non-null     object
 5   Marks                  10 non-null     int64
 6   Attendance_Percentage  10 non-null     int64
dtypes: int64(4), object(3)
memory usage: 692.0+ bytes

Statistical Summary

       Student_ID        Age      Marks  Attendance_Percentage
count    10.00000  10.000000  10.000000              10.000000
mean      5.50000  22.700000  76.800000              82.600000
std       3.02765   1.337494  18.023442              12.294534
min       1.00000  21.000000  39.000000              60.000000
25%       3.25000  22.000000  70.750000              74.250000
50%       5.50000  22.500000  81.500000              86.000000
75%       7.75000  23.750000  90.250000              91.250000
max      10.00000  25.000000  95.000000              97.000000

In [ ]:
display(df[df["Marks"]>90])

   Student_ID    Name  Age   City        Course  Marks  Attendance_Percentage
1           2   Priya   24  Delhi  Data Science     92                     88
5           6  Simran   22  Delhi  Data Science     91                     89
9          10   Sneha   22  Delhi        Python     95                     97

In [ ]:
display(df[df["Attendance_Percentage"]<75])

   Student_ID    Name  Age    City        Course  Marks  Attendance_Percentage
4           5   Rohan   25   Patna        Python     69                     72
6           7  Vikash   24   Patna     Analytics     55                     68
8           9   Arjun   23  Mumbai  Data Science     39                     60

In [ ]:
display(df[df["City"]=="Patna"])

   Student_ID    Name  Age   City     Course  Marks  Attendance_Percentage
0           1   Rahul   22  Patna     Python     85                     92
4           5   Rohan   25  Patna     Python     69                     72
6           7  Vikash   24  Patna  Analytics     55                     68

In [ ]:
display(df.sort_values(by="Attendance_Percentage",ascending=False))

,Student_ID,Name,Age,City,Course,Marks,Attendance_Percentage
9,10,Sneha,22,Delhi,Python,95,97
3,4,Neha,23,Mumbai,Analytics,88,95
0,1,Rahul,22,Patna,Python,85,92
5,6,Simran,22,Delhi,Data Science,91,89
1,2,Priya,24,Delhi,Data Science,92,88
7,8,Pooja,21,Kolkata,Python,78,84
2,3,Aman,21,Kolkata,Python,76,81
4,5,Rohan,25,Patna,Python,69,72
6,7,Vikash,24,Patna,Analytics,55,68
8,9,Arjun,23,Mumbai,Data Science,39,60

In [ ]:
df["Result"] = df["Marks"].apply(lambda x: "Pass" if x>40 else "Fail")

In [ ]:
df

,Student_ID,Name,Age,City,Course,Marks,Attendance_Percentage,Result
0,1,Rahul,22,Patna,Python,85,92,Pass
1,2,Priya,24,Delhi,Data Science,92,88,Pass
2,3,Aman,21,Kolkata,Python,76,81,Pass
3,4,Neha,23,Mumbai,Analytics,88,95,Pass
4,5,Rohan,25,Patna,Python,69,72,Pass
5,6,Simran,22,Delhi,Data Science,91,89,Pass
6,7,Vikash,24,Patna,Analytics,55,68,Pass
7,8,Pooja,21,Kolkata,Python,78,84,Pass
8,9,Arjun,23,Mumbai,Data Science,39,60,Fail
9,10,Sneha,22,Delhi,Python,95,97,Pass

In [ ]:
def grade(marks):

    if marks>=90:
        return "A+"

    elif marks>=75:
        return "A"

    elif marks>=60:
        return "B"

    elif marks>=40:
        return "C"

    else:
        return "Fail"

df["Grade"]=df["Marks"].apply(grade)

In [ ]:
df

,Student_ID,Name,Age,City,Course,Marks,Attendance_Percentage,Result,Grade
0,1,Rahul,22,Patna,Python,85,92,Pass,A
1,2,Priya,24,Delhi,Data Science,92,88,Pass,A+
2,3,Aman,21,Kolkata,Python,76,81,Pass,A
3,4,Neha,23,Mumbai,Analytics,88,95,Pass,A
4,5,Rohan,25,Patna,Python,69,72,Pass,B
5,6,Simran,22,Delhi,Data Science,91,89,Pass,A+
6,7,Vikash,24,Patna,Analytics,55,68,Pass,C
7,8,Pooja,21,Kolkata,Python,78,84,Pass,A
8,9,Arjun,23,Mumbai,Data Science,39,60,Fail,Fail
9,10,Sneha,22,Delhi,Python,95,97,Pass,A+

In [ ]:
df["Attendance_Status"] = df["Attendance_Percentage"].apply(
    lambda x:"Eligible" if x>=75 else "Low Attendance"
)

display(df)

,Student_ID,Name,Age,City,Course,Marks,Attendance_Percentage,Result,Grade,Attendance_Status
0,1,Rahul,22,Patna,Python,85,92,Pass,A,Eligible
1,2,Priya,24,Delhi,Data Science,92,88,Pass,A+,Eligible
2,3,Aman,21,Kolkata,Python,76,81,Pass,A,Eligible
3,4,Neha,23,Mumbai,Analytics,88,95,Pass,A,Eligible
4,5,Rohan,25,Patna,Python,69,72,Pass,B,Low Attendance
5,6,Simran,22,Delhi,Data Science,91,89,Pass,A+,Eligible
6,7,Vikash,24,Patna,Analytics,55,68,Pass,C,Low Attendance
7,8,Pooja,21,Kolkata,Python,78,84,Pass,A,Eligible
8,9,Arjun,23,Mumbai,Data Science,39,60,Fail,Fail,Low Attendance
9,10,Sneha,22,Delhi,Python,95,97,Pass,A+,Eligible

In [ ]:
display(df.groupby("Course")["Marks"].min())

Course
Analytics       55
Data Science    39
Python          69
Name: Marks, dtype: int64

In [ ]:
summary = pd.DataFrame({

"Metric":[
"Total Students",
"Average Marks",
"Highest Marks",
"Lowest Marks",
"Passed Students",
"Failed Students",
"Students with Low Attendance",
"Students Scoring Above 80"
],

"Value":[

len(df),

round(df["Marks"].mean(),2),

df["Marks"].max(),

df["Marks"].min(),

len(df[df["Result"]=="Pass"]),

len(df[df["Result"]=="Fail"]),

len(df[df["Attendance_Status"]=="Low Attendance"]),

len(df[df["Marks"]>80])

]

})

display(summary)

                         Metric  Value
0                Total Students   10.0
1                 Average Marks   76.8
2                 Highest Marks   95.0
3                  Lowest Marks   39.0
4               Passed Students    9.0
5               Failed Students    1.0
6  Students with Low Attendance    3.0
7     Students Scoring Above 80    5.0

In [ ]:
df.to_csv("final_student_performance_report.csv", index=False)

print("final_student_performance_report.csv created successfully.")

final_student_performance_report.csv created successfully.

In [ ]:
final_df = pd.read_csv("final_student_performance_report.csv")

display(final_df)

,Student_ID,Name,Age,City,Course,Marks,Attendance_Percentage,Result,Grade,Attendance_Status
0,1,Rahul,22,Patna,Python,85,92,Pass,A,Eligible
1,2,Priya,24,Delhi,Data Science,92,88,Pass,A+,Eligible
2,3,Aman,21,Kolkata,Python,76,81,Pass,A,Eligible
3,4,Neha,23,Mumbai,Analytics,88,95,Pass,A,Eligible
4,5,Rohan,25,Patna,Python,69,72,Pass,B,Low Attendance
5,6,Simran,22,Delhi,Data Science,91,89,Pass,A+,Eligible
6,7,Vikash,24,Patna,Analytics,55,68,Pass,C,Low Attendance
7,8,Pooja,21,Kolkata,Python,78,84,Pass,A,Eligible
8,9,Arjun,23,Mumbai,Data Science,39,60,Fail,Fail,Low Attendance
9,10,Sneha,22,Delhi,Python,95,97,Pass,A+,Eligible