<a href="https://colab.research.google.com/github/dsatish1252/sqlite-python-implementation/blob/main/Retail_Sales_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Retail Sales Data Analysis

### 1. Import Libraries

In [1]:
import sqlite3
import pandas as pd

### 2. Connect to SQLite Database

In [2]:
conn = sqlite3.connect("retail_sales.db")

cursor = conn.cursor()

print("Database Created Successfully")

Database Created Successfully

### 3. Create Customers Table

In [3]:
cursor.execute("""
CREATE TABLE customers(
    customer_id TEXT PRIMARY KEY,
    customer_name TEXT,
    city TEXT,
    age INTEGER,
    gender TEXT
)
""")

### 4. Create Products Table

In [6]:
cursor.execute("""
CREATE TABLE products(
    product_id TEXT PRIMARY KEY,
    product_name TEXT,
    category TEXT,
    price REAL
)
""")

### 5. Create Orders Table

In [8]:
cursor.execute("""
CREATE TABLE orders(
    order_id TEXT PRIMARY KEY,
    customer_id TEXT,
    product_id TEXT,
    order_date DATE,
    quantity INTEGER,
    sales_channel TEXT,

    FOREIGN KEY(customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY(product_id) REFERENCES products(product_id)
)
""")

### 6. Commit Table Creations

In [9]:
conn.commit()

print("Tables Created Successfully")

Tables Created Successfully

### 7. Insert Sample Data

In [10]:
# -------------------------------
# Insert Data into Customers Table
# -------------------------------

customers = [
    ("C001", "Rahul Sharma", "Patna", 32, "Male"),
    ("C002", "Priya Singh", "Delhi", 28, "Female"),
    ("C003", "Amit Kumar", "Kolkata", 35, "Male"),
    ("C004", "Sneha Verma", "Pune", 30, "Female"),
    ("C005", "Rohit Raj", "Patna", 40, "Male"),
    ("C006", "Neha Gupta", "Delhi", 26, "Female"),
    ("C007", "Ankit Sinha", "Mumbai", 38, "Male"),
    ("C008", "Riya Das", "Kolkata", 24, "Female")
]

cursor.executemany("""
INSERT INTO customers
VALUES (?, ?, ?, ?, ?)
""", customers)


# -------------------------------
# Insert Data into Products Table
# -------------------------------

products = [
    ("P001", "Laptop", "Electronics", 55000),
    ("P002", "Mobile Phone", "Electronics", 25000),
    ("P003", "Office Chair", "Furniture", 7000),
    ("P004", "Headphones", "Electronics", 3000),
    ("P005", "Study Table", "Furniture", 12000),
    ("P006", "Shoes", "Fashion", 4000),
    ("P007", "Backpack", "Fashion", 2500)
]

cursor.executemany("""
INSERT INTO products
VALUES (?, ?, ?, ?)
""", products)


# -------------------------------
# Insert Data into Orders Table
# -------------------------------

orders = [
    ("O001", "C001", "P002", "2026-01-10", 2, "Online"),
    ("O002", "C002", "P001", "2026-01-15", 1, "Offline"),
    ("O003", "C003", "P004", "2026-02-05", 3, "Online"),
    ("O004", "C004", "P003", "2026-02-12", 2, "Offline"),
    ("O005", "C005", "P006", "2026-03-01", 4, "Online"),
    ("O006", "C001", "P004", "2026-03-08", 2, "Online"),
    ("O007", "C006", "P005", "2026-03-18", 1, "Offline"),
    ("O008", "C007", "P001", "2026-04-02", 1, "Online"),
    ("O009", "C008", "P007", "2026-04-10", 5, "Online"),
    ("O010", "C003", "P002", "2026-04-22", 1, "Offline"),
    ("O011", "C005", "P003", "2026-05-05", 1, "Offline"),
    ("O012", "C002", "P004", "2026-05-15", 4, "Online")
]

cursor.executemany("""
INSERT INTO orders
VALUES (?, ?, ?, ?, ?, ?)
""", orders)

# Save all changes
conn.commit()

print("All sample data inserted successfully!")

All sample data inserted successfully!

### 8. Display Customers Data (SQL)

In [11]:
pd.read_sql("SELECT * FROM customers", conn)

  customer_id customer_name     city  age  gender
0        C001  Rahul Sharma    Patna   32    Male
1        C002   Priya Singh    Delhi   28  Female
2        C003    Amit Kumar  Kolkata   35    Male
3        C004   Sneha Verma     Pune   30  Female
4        C005     Rohit Raj    Patna   40    Male
5        C006    Neha Gupta    Delhi   26  Female
6        C007   Ankit Sinha   Mumbai   38    Male
7        C008      Riya Das  Kolkata   24  Female

### 9. Display Products Data (SQL)

In [12]:
pd.read_sql("SELECT * FROM products", conn)

  product_id  product_name     category    price
0       P001        Laptop  Electronics  55000.0
1       P002  Mobile Phone  Electronics  25000.0
2       P003  Office Chair    Furniture   7000.0
3       P004    Headphones  Electronics   3000.0
4       P005   Study Table    Furniture  12000.0
5       P006         Shoes      Fashion   4000.0
6       P007      Backpack      Fashion   2500.0

### 10. Display Orders Data (SQL)

In [13]:
pd.read_sql("SELECT * FROM orders", conn)

   order_id customer_id product_id  order_date  quantity sales_channel
0      O001        C001       P002  2026-01-10         2        Online
1      O002        C002       P001  2026-01-15         1       Offline
2      O003        C003       P004  2026-02-05         3        Online
3      O004        C004       P003  2026-02-12         2       Offline
4      O005        C005       P006  2026-03-01         4        Online
5      O006        C001       P004  2026-03-08         2        Online
6      O007        C006       P005  2026-03-18         1       Offline
7      O008        C007       P001  2026-04-02         1        Online
8      O009        C008       P007  2026-04-10         5        Online
9      O010        C003       P002  2026-04-22         1       Offline
10     O011        C005       P003  2026-05-05         1       Offline
11     O012        C002       P004  2026-05-15         4        Online

### 11. Retrieve Joined Sales Data (SQL)

In [15]:
query = """
SELECT
    o.order_id,
    c.customer_name,
    c.city,
    p.product_name,
    p.category,
    o.quantity,
    p.price,
    (o.quantity * p.price) AS total_amount,
    o.sales_channel,
    o.order_date
FROM orders o
JOIN customers c
ON o.customer_id = c.customer_id
JOIN products p
ON o.product_id = p.product_id
ORDER BY c.customer_name;
"""

pd.read_sql(query, conn)

,order_id,customer_name,city,product_name,category,quantity,price,total_amount,sales_channel,order_date
0,O003,Amit Kumar,Kolkata,Headphones,Electronics,3,3000.0,9000.0,Online,2026-02-05
1,O010,Amit Kumar,Kolkata,Mobile Phone,Electronics,1,25000.0,25000.0,Offline,2026-04-22
2,O008,Ankit Sinha,Mumbai,Laptop,Electronics,1,55000.0,55000.0,Online,2026-04-02
3,O007,Neha Gupta,Delhi,Study Table,Furniture,1,12000.0,12000.0,Offline,2026-03-18
4,O002,Priya Singh,Delhi,Laptop,Electronics,1,55000.0,55000.0,Offline,2026-01-15
5,O012,Priya Singh,Delhi,Headphones,Electronics,4,3000.0,12000.0,Online,2026-05-15
6,O001,Rahul Sharma,Patna,Mobile Phone,Electronics,2,25000.0,50000.0,Online,2026-01-10
7,O006,Rahul Sharma,Patna,Headphones,Electronics,2,3000.0,6000.0,Online,2026-03-08
8,O009,Riya Das,Kolkata,Backpack,Fashion,5,2500.0,12500.0,Online,2026-04-10
9,O005,Rohit Raj,Patna,Shoes,Fashion,4,4000.0,16000.0,Online,2026-03-01
10,O011,Rohit Raj,Patna,Office Chair,Furniture,1,7000.0,7000.0,Offline,2026-05-05
11,O004,Sneha Verma,Pune,Office Chair,Furniture,2,7000.0,14000.0,Offline,2026-02-12

### 12. Calculate Total Revenue (SQL)

In [19]:
query = """
select
sum(o.quantity * p.price) as total_revenue
from orders o
join products p
on o.product_id = p.product_id;
"""

pd.read_sql(query, conn)

   total_revenue
0       273500.0

### 13. Analyze Revenue by City (SQL)

In [20]:
query = """
SELECT
    c.city,
    SUM(o.quantity * p.price) AS total_revenue
FROM orders o
JOIN customers c
ON o.customer_id = c.customer_id
JOIN products p
ON o.product_id = p.product_id
GROUP BY c.city
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, conn)

      city  total_revenue
0    Patna        79000.0
1    Delhi        79000.0
2   Mumbai        55000.0
3  Kolkata        46500.0
4     Pune        14000.0

### 14. Find Best-Selling Product (SQL)

In [21]:
query = """
SELECT
    p.product_name,
    SUM(o.quantity) AS total_quantity_sold
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_quantity_sold DESC
LIMIT 1;
"""

pd.read_sql(query, conn)

  product_name  total_quantity_sold
0   Headphones                    9

### 15. Analyze Category-wise Revenue (SQL)

In [22]:
query = """
SELECT
    p.category,
    SUM(o.quantity * p.price) AS total_revenue
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY p.category
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, conn)

      category  total_revenue
0  Electronics       212000.0
1    Furniture        33000.0
2      Fashion        28500.0

### 16. Analyze Revenue by Sales Channel (SQL)

In [23]:
query = """
SELECT
    o.sales_channel,
    SUM(o.quantity * p.price) AS total_revenue
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY o.sales_channel
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, conn)

  sales_channel  total_revenue
0        Online       160500.0
1       Offline       113000.0

### 17. Analyze Monthly Revenue Trend (SQL)

In [24]:
query = """
SELECT
    strftime('%Y-%m', o.order_date) AS month,
    SUM(o.quantity * p.price) AS total_revenue
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY month
ORDER BY month;
"""

pd.read_sql(query, conn)

     month  total_revenue
0  2026-01       105000.0
1  2026-02        23000.0
2  2026-03        34000.0
3  2026-04        92500.0
4  2026-05        19000.0

### 18. Identify High-Value Customers (SQL)

In [25]:
query = """
SELECT
    c.customer_name,
    c.city,
    SUM(o.quantity * p.price) AS total_purchase_value
FROM orders o
JOIN customers c
ON o.customer_id = c.customer_id
JOIN products p
ON o.product_id = p.product_id
GROUP BY c.customer_name, c.city
HAVING SUM(o.quantity * p.price) > 50000
ORDER BY total_purchase_value DESC;
"""

pd.read_sql(query, conn)

  customer_name    city  total_purchase_value
0   Priya Singh   Delhi               67000.0
1  Rahul Sharma   Patna               56000.0
2   Ankit Sinha  Mumbai               55000.0

### 19. Load Data into Pandas DataFrames

In [26]:
import pandas as pd

customers_df = pd.read_sql("SELECT * FROM customers", conn)
products_df = pd.read_sql("SELECT * FROM products", conn)
orders_df = pd.read_sql("SELECT * FROM orders", conn)

print("Customers DataFrame")
display(customers_df)

print("Products DataFrame")
display(products_df)

print("Orders DataFrame")
display(orders_df)

Customers DataFrame

  customer_id customer_name     city  age  gender
0        C001  Rahul Sharma    Patna   32    Male
1        C002   Priya Singh    Delhi   28  Female
2        C003    Amit Kumar  Kolkata   35    Male
3        C004   Sneha Verma     Pune   30  Female
4        C005     Rohit Raj    Patna   40    Male
5        C006    Neha Gupta    Delhi   26  Female
6        C007   Ankit Sinha   Mumbai   38    Male
7        C008      Riya Das  Kolkata   24  Female

Products DataFrame

  product_id  product_name     category    price
0       P001        Laptop  Electronics  55000.0
1       P002  Mobile Phone  Electronics  25000.0
2       P003  Office Chair    Furniture   7000.0
3       P004    Headphones  Electronics   3000.0
4       P005   Study Table    Furniture  12000.0
5       P006         Shoes      Fashion   4000.0
6       P007      Backpack      Fashion   2500.0

Orders DataFrame

   order_id customer_id product_id  order_date  quantity sales_channel
0      O001        C001       P002  2026-01-10         2        Online
1      O002        C002       P001  2026-01-15         1       Offline
2      O003        C003       P004  2026-02-05         3        Online
3      O004        C004       P003  2026-02-12         2       Offline
4      O005        C005       P006  2026-03-01         4        Online
5      O006        C001       P004  2026-03-08         2        Online
6      O007        C006       P005  2026-03-18         1       Offline
7      O008        C007       P001  2026-04-02         1        Online
8      O009        C008       P007  2026-04-10         5        Online
9      O010        C003       P002  2026-04-22         1       Offline
10     O011        C005       P003  2026-05-05         1       Offline
11     O012        C002       P004  2026-05-15         4        Online

### 20. Merge DataFrames to Create Sales DataFrame

In [27]:
sales_df = pd.merge(
    orders_df,
    customers_df,
    on="customer_id",
    how="inner"
)

sales_df = pd.merge(
    sales_df,
    products_df,
    on="product_id",
    how="inner"
)

print("Merged Sales DataFrame")
display(sales_df)

Merged Sales DataFrame

,order_id,customer_id,product_id,order_date,quantity,sales_channel,customer_name,city,age,gender,product_name,category,price
0,O001,C001,P002,2026-01-10,2,Online,Rahul Sharma,Patna,32,Male,Mobile Phone,Electronics,25000.0
1,O002,C002,P001,2026-01-15,1,Offline,Priya Singh,Delhi,28,Female,Laptop,Electronics,55000.0
2,O003,C003,P004,2026-02-05,3,Online,Amit Kumar,Kolkata,35,Male,Headphones,Electronics,3000.0
3,O004,C004,P003,2026-02-12,2,Offline,Sneha Verma,Pune,30,Female,Office Chair,Furniture,7000.0
4,O005,C005,P006,2026-03-01,4,Online,Rohit Raj,Patna,40,Male,Shoes,Fashion,4000.0
5,O006,C001,P004,2026-03-08,2,Online,Rahul Sharma,Patna,32,Male,Headphones,Electronics,3000.0
6,O007,C006,P005,2026-03-18,1,Offline,Neha Gupta,Delhi,26,Female,Study Table,Furniture,12000.0
7,O008,C007,P001,2026-04-02,1,Online,Ankit Sinha,Mumbai,38,Male,Laptop,Electronics,55000.0
8,O009,C008,P007,2026-04-10,5,Online,Riya Das,Kolkata,24,Female,Backpack,Fashion,2500.0
9,O010,C003,P002,2026-04-22,1,Offline,Amit Kumar,Kolkata,35,Male,Mobile Phone,Electronics,25000.0
10,O011,C005,P003,2026-05-05,1,Offline,Rohit Raj,Patna,40,Male,Office Chair,Furniture,7000.0
11,O012,C002,P004,2026-05-15,4,Online,Priya Singh,Delhi,28,Female,Headphones,Electronics,3000.0

### 21. Calculate Total Amount for Each Order

In [28]:
sales_df["total_amount"] = sales_df["quantity"] * sales_df["price"]

print("Sales DataFrame with Total Amount")
display(sales_df)

Sales DataFrame with Total Amount

,order_id,customer_id,product_id,order_date,quantity,sales_channel,customer_name,city,age,gender,product_name,category,price,total_amount
0,O001,C001,P002,2026-01-10,2,Online,Rahul Sharma,Patna,32,Male,Mobile Phone,Electronics,25000.0,50000.0
1,O002,C002,P001,2026-01-15,1,Offline,Priya Singh,Delhi,28,Female,Laptop,Electronics,55000.0,55000.0
2,O003,C003,P004,2026-02-05,3,Online,Amit Kumar,Kolkata,35,Male,Headphones,Electronics,3000.0,9000.0
3,O004,C004,P003,2026-02-12,2,Offline,Sneha Verma,Pune,30,Female,Office Chair,Furniture,7000.0,14000.0
4,O005,C005,P006,2026-03-01,4,Online,Rohit Raj,Patna,40,Male,Shoes,Fashion,4000.0,16000.0
5,O006,C001,P004,2026-03-08,2,Online,Rahul Sharma,Patna,32,Male,Headphones,Electronics,3000.0,6000.0
6,O007,C006,P005,2026-03-18,1,Offline,Neha Gupta,Delhi,26,Female,Study Table,Furniture,12000.0,12000.0
7,O008,C007,P001,2026-04-02,1,Online,Ankit Sinha,Mumbai,38,Male,Laptop,Electronics,55000.0,55000.0
8,O009,C008,P007,2026-04-10,5,Online,Riya Das,Kolkata,24,Female,Backpack,Fashion,2500.0,12500.0
9,O010,C003,P002,2026-04-22,1,Offline,Amit Kumar,Kolkata,35,Male,Mobile Phone,Electronics,25000.0,25000.0
10,O011,C005,P003,2026-05-05,1,Offline,Rohit Raj,Patna,40,Male,Office Chair,Furniture,7000.0,7000.0
11,O012,C002,P004,2026-05-15,4,Online,Priya Singh,Delhi,28,Female,Headphones,Electronics,3000.0,12000.0

### 22. Calculate Total Revenue (Pandas)

In [29]:
total_revenue = sales_df["total_amount"].sum()

print("Total Revenue")
print(total_revenue)

Total Revenue
273500.0

### 23. Analyze Revenue by City (Pandas)

In [30]:
city_revenue = (
    sales_df
    .groupby("city")["total_amount"]
    .sum()
    .reset_index()
    .sort_values(by="total_amount", ascending=False)
)

print("Revenue by City")
display(city_revenue)

Revenue by City

      city  total_amount
0    Delhi       79000.0
3    Patna       79000.0
2   Mumbai       55000.0
1  Kolkata       46500.0
4     Pune       14000.0

### 24. Analyze Product-wise Quantity Sold (Pandas)

In [31]:
product_sales = (
    sales_df
    .groupby("product_name")["quantity"]
    .sum()
    .reset_index()
    .sort_values(by="quantity", ascending=False)
)

print("Product-wise Quantity Sold")
display(product_sales)

Product-wise Quantity Sold

   product_name  quantity
1    Headphones         9
0      Backpack         5
5         Shoes         4
4  Office Chair         3
3  Mobile Phone         3
2        Laptop         2
6   Study Table         1

### 25. Analyze Category-wise Revenue (Pandas)

In [32]:
category_revenue = (
    sales_df
    .groupby("category")["total_amount"]
    .sum()
    .reset_index()
    .sort_values(by="total_amount", ascending=False)
)

print("Category-wise Revenue")
display(category_revenue)

Category-wise Revenue

      category  total_amount
0  Electronics      212000.0
2    Furniture       33000.0
1      Fashion       28500.0

### 26. Analyze Revenue by Sales Channel (Pandas)

In [33]:
channel_revenue = (
    sales_df
    .groupby("sales_channel")["total_amount"]
    .sum()
    .reset_index()
    .sort_values(by="total_amount", ascending=False)
)

print("Revenue by Sales Channel")
display(channel_revenue)

Revenue by Sales Channel

  sales_channel  total_amount
1        Online      160500.0
0       Offline      113000.0

### 27. Analyze Monthly Revenue Trend (Pandas)

In [34]:
sales_df["order_date"] = pd.to_datetime(sales_df["order_date"])

sales_df["month"] = sales_df["order_date"].dt.strftime("%Y-%m")

monthly_revenue = (
    sales_df
    .groupby("month")["total_amount"]
    .sum()
    .reset_index()
    .sort_values(by="month")
)

print("Monthly Revenue Trend")
display(monthly_revenue)

Monthly Revenue Trend

     month  total_amount
0  2026-01      105000.0
1  2026-02       23000.0
2  2026-03       34000.0
3  2026-04       92500.0
4  2026-05       19000.0

### 28. Identify High-Value Customers (Pandas)

In [35]:
high_value_customers = (
    sales_df
    .groupby(["customer_name", "city"])["total_amount"]
    .sum()
    .reset_index()
)

high_value_customers = high_value_customers[
    high_value_customers["total_amount"] > 50000
]

high_value_customers = high_value_customers.sort_values(
    by="total_amount",
    ascending=False
)

print("High-Value Customers")
display(high_value_customers)

High-Value Customers

  customer_name    city  total_amount
3   Priya Singh   Delhi       67000.0
4  Rahul Sharma   Patna       56000.0
1   Ankit Sinha  Mumbai       55000.0

### 29. Final Sales DataFrame

In [36]:
print("Final Sales DataFrame")
display(sales_df)

Final Sales DataFrame

,order_id,customer_id,product_id,order_date,quantity,sales_channel,customer_name,city,age,gender,product_name,category,price,total_amount,month
0,O001,C001,P002,2026-01-10,2,Online,Rahul Sharma,Patna,32,Male,Mobile Phone,Electronics,25000.0,50000.0,2026-01
1,O002,C002,P001,2026-01-15,1,Offline,Priya Singh,Delhi,28,Female,Laptop,Electronics,55000.0,55000.0,2026-01
2,O003,C003,P004,2026-02-05,3,Online,Amit Kumar,Kolkata,35,Male,Headphones,Electronics,3000.0,9000.0,2026-02
3,O004,C004,P003,2026-02-12,2,Offline,Sneha Verma,Pune,30,Female,Office Chair,Furniture,7000.0,14000.0,2026-02
4,O005,C005,P006,2026-03-01,4,Online,Rohit Raj,Patna,40,Male,Shoes,Fashion,4000.0,16000.0,2026-03
5,O006,C001,P004,2026-03-08,2,Online,Rahul Sharma,Patna,32,Male,Headphones,Electronics,3000.0,6000.0,2026-03
6,O007,C006,P005,2026-03-18,1,Offline,Neha Gupta,Delhi,26,Female,Study Table,Furniture,12000.0,12000.0,2026-03
7,O008,C007,P001,2026-04-02,1,Online,Ankit Sinha,Mumbai,38,Male,Laptop,Electronics,55000.0,55000.0,2026-04
8,O009,C008,P007,2026-04-10,5,Online,Riya Das,Kolkata,24,Female,Backpack,Fashion,2500.0,12500.0,2026-04
9,O010,C003,P002,2026-04-22,1,Offline,Amit Kumar,Kolkata,35,Male,Mobile Phone,Electronics,25000.0,25000.0,2026-04
10,O011,C005,P003,2026-05-05,1,Offline,Rohit Raj,Patna,40,Male,Office Chair,Furniture,7000.0,7000.0,2026-05
11,O012,C002,P004,2026-05-15,4,Online,Priya Singh,Delhi,28,Female,Headphones,Electronics,3000.0,12000.0,2026-05

### 30. Business Insights Summary

In [37]:
print("BUSINESS INSIGHTS")
print("-" * 50)

print(f"1. Total Revenue: ₹{sales_df['total_amount'].sum():,.0f}")

print(f"2. Highest Revenue City: {city_revenue.iloc[0]['city']}")

print(f"3. Best Selling Product: {product_sales.iloc[0]['product_name']}")

print(f"4. Best Performing Category: {category_revenue.iloc[0]['category']}")

print(f"5. Better Sales Channel: {channel_revenue.iloc[0]['sales_channel']}")

print(f"6. Highest Revenue Month: {monthly_revenue.iloc[monthly_revenue['total_amount'].idxmax()]['month']}")

print("7. High Value Customers:")
display(high_value_customers)

BUSINESS INSIGHTS
--------------------------------------------------
1. Total Revenue: ₹273,500
2. Highest Revenue City: Delhi
3. Best Selling Product: Headphones
4. Best Performing Category: Electronics
5. Better Sales Channel: Online
6. Highest Revenue Month: 2026-01
7. High Value Customers:

  customer_name    city  total_amount
3   Priya Singh   Delhi       67000.0
4  Rahul Sharma   Patna       56000.0
1   Ankit Sinha  Mumbai       55000.0